CBIIT/crdc-datahub-models

CDS/1.3.0/README.md
ICDC/1.0.0/Data_Model_Navigator_README.md

This PR replaces the relative links in the CDS and ICDC README files with a link to https://datacommons.cancer.gov/
N/A
https://tracker.nci.nih.gov/browse/CRDCDH-636

CRDCDH-636 Replace relative URLs

---

CTDC/1.0.0/README.md
CTDC/1.0.0/ctdc_model_file.yaml
CTDC/1.0.0/ctdc_model_properties_file.yaml
content.json

Add CTDC model at version 1.0.0 using the CDS model readme (per Todd).
We still don't have the loading files.
https://tracker.nci.nih.gov/browse/CRDCDH-1299
https://tracker.nci.nih.gov/browse/CRDCDH-1298

CTDC v1.0.0

---

content.json

Add this new key for file ID generation tickets.

Add omit-DCF-prefix for ICDC

---

ICDC/1.0.0/icdc-model-props.yml
ICDC/1.0.0/icdc-model.yml

This PR adds a key for each node so that validation of data submissions will be possible. This version of the data model is not yet merged to the develop branch in the icdc-datamodel repo.

CRDCDH-1344

---

cache/CTDC/1.0.0/ctdc_model_properties_file.yaml

Copied from CTDC commit https://github.com/CBIIT/ctdc-model/commit/467214a419765c14de0500128aa31233586eb928
Original PR https://github.com/CBIIT/ctdc-model/pull/21

Update CTDC props

---

cache/ICDC/1.0.0/icdc-model-props.yml

https://github.com/CBIIT/icdc-model-tool/commit/3eb03b4fd159409dab0db4b36e9d26ed1f8d1d50

Update ICDC props

---

.github/workflows/update-model-version.yaml

1. change action name for staging all files
2. updated GitHub action committer

Github Action Update

---

cache/ICDC/1.0.0/icdc-model-props.yml

https://github.com/CBIIT/icdc-model-tool/commit/76b42b09414e26d59cf777dd3a02dc3022711e89

Manual update ICDC Model Props

---

.github/workflows/update-model-version.yaml

Prepend to the Version array and remove duplicate versions.

CRDCDH-1335

---

cache/CTDC/1.0.0/ctdc_model_file.yaml
cache/CTDC/1.0.0/ctdc_model_properties_file.yaml

Sync CTDC Model changes from PR https://github.com/CBIIT/ctdc-model/pull/23

Manual update of CTDC model

---

cache/CTDC/1.0.0/ctdc_model_file.yaml
cache/CTDC/1.0.0/ctdc_model_properties_file.yaml

Includes commits https://github.com/CBIIT/ctdc-model/compare/a92a7e13ebbee9fa11b324c97d406d0f5a9c316e...6f7d390706847ac696fbe847a95ca41f998e8aeb

Sync CTDC Data Model

---

.github/workflows/update-model-version.yaml

Added Github Matrix
- Runs the workflow on each specified branch

CRDCDH-1597

---

cache/CTDC/1.0.0/ctdc_model_file.yaml
cache/CTDC/1.0.0/ctdc_model_properties_file.yaml

Up to commit https://github.com/CBIIT/ctdc-model/commit/aa4ddd44a93f2e53c670675a19c47c317797b9ff

Manual CTDC Model Sync

---

cache/CTDC/1.0.0/ctdc_model_properties_file.yaml

https://github.com/CBIIT/ctdc-model/commit/0830d2649b3424040c3dd2d637297d289f768be3

Manual CTDC Sync

---

.github/workflows/update-model-version.yaml

CRDCDH-1598

---

.github/workflows/update-model-version.yaml

Removed 'true'

---

.github/workflows/update-model-version.yaml

It will refresh the sub-module with the latest updates."

Refresh Submodule

---

.github/workflows/update-model-version.yaml

Printing Submodule Branch

---

.github/workflows/update-model-version.yaml

It will continuously monitor for any updates compared to the current model/property files. The GitHub action is only triggered if the version is updated in the file. However, this PR change the logic that the cache files differ from the model files in the submodule, even without a version change.

File Updated Without Version Change

---

.github/workflows/update-model-version.yaml

Commented other branches since the content.json has changed.
Detect any file change after overwritten all files from the model in the submodule.

CRDCDH-2052

---

.github/workflows/update-model-version.yaml

Sync content of model-navigator-resources folder

Sync content of model-navigator-resources folder
